### ISSUE TITLE
Question: Why can't I return void? 

### ISSUE THREAD

**Issue by igormidev** [Flutterando/result_dart#11]
Why does the return need to be an object? If I have an "upload data" function and that method just updates an info in the server and dosen't return anything, I still am forced to return an object in success instead of being able to return void

**Comment by Mairramer** [comment]
@igormidev When you don't want to return a value just do something like:

```
Result<void, Exception> getSomethingPretty() {
   return Result.success(unit);
}
```

**Comment by jacobaraujo7** [comment]
Return Unit instead void
