### ISSUE TITLE
result_dart will accept void as paramenter type for success?

### ISSUE THREAD

**Issue by mattsouza26** [Flutterando/result_dart#2]
**when I try to use void as a success parameter it is not allowed.**
example:
![image](https://user-images.githubusercontent.com/74125222/210642425-10a48e38-0399-467a-a750-a4302a5a7741.png)
![image](https://user-images.githubusercontent.com/74125222/210642494-4579178b-b285-4ebd-9db5-6ae451bc25c2.png)

**Comment by marcellocamara** [comment]
@mattsouza26 try this, instead of use void:

![Captura de Tela 2023-01-25 às 00 39 28](https://user-images.githubusercontent.com/18273071/214474887-c95ff074-a1bd-46ae-aadf-f01248752d26.png)

**Comment by mattsouza26** [comment]
> @mattsouza26 try this, instead of use void:
> 
> ![Captura de Tela 2023-01-25 às 00 39 28](https://user-images.githubusercontent.com/18273071/214474887-c95ff074-a1bd-46ae-aadf-f01248752d26.png)

thanks, this works but it's not very clear to read, i'll continue to use multiple_result instead.

**Comment by jacobaraujo7** [comment]
@mattsouza26 I added Unit in multiple_result :)
Good use!
