### ISSUE TITLE
Const constructors are not being returned from factories in result.dart

### ISSUE THREAD

**Issue by eKaramihov** [Flutterando/result_dart#3]
Hi, I really like the package and I have a suggestion for improvement

The factories in the Result class can not return a const Constructor, even tho the Success and Failure class have one.

I managed to by pass this problem, by declaring the factory constructor this way:

const factory Result.success(S s) = Success;
const factory Result.failure(F e) = Failure;

**Comment by jacobaraujo7** [comment]
fiexed
